[package]
name = "azoya_cw_multi_test_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.0.0" }
cw-multi-test = "0.13.2"


[dev-dependencies]
